### Create a new Patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Hari Om Prabhu",
  "email": "hariomprabhu@example.com",
  "address": "1234 main street",
  "dateOfBirth": "1994-09-09",
  "registeredDate": "2025-11-14"
}

###